#!/usr/bin/env python3
"""
Fine-tune GraphCodeBERT for SV/UVM NER — full 32-kind label set.

Usage:
    PYTHONUNBUFFERED=1 python train_ner_v2.py [data_path]

Data:   /tmp/ner_data_v2.jsonl   (generated by generate_ner_data.py)
Output: /Users/aditya/azath-model/ner_v2/
"""

import json, random, sys
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoModelForTokenClassification,
    AutoTokenizer,
    get_linear_schedule_with_warmup,
)
from seqeval.metrics import classification_report, f1_score

# ── Config ────────────────────────────────────────────────────────────────────

MODEL_NAME   = "microsoft/graphcodebert-base"
DATA_PATH    = sys.argv[1] if len(sys.argv) > 1 else "/tmp/ner_data_v2.jsonl"
OUT_DIR      = "/Users/aditya/azath-model/ner_v2"
EPOCHS       = 5
BATCH_SIZE   = 16           # larger batch → fewer steps → faster on MPS
LR           = 2e-5
WARMUP_RATIO = 0.06
TRAIN_SPLIT  = 0.85
SEED         = 42
LOG_EVERY    = 100          # print loss every N steps

# ── Label set ─────────────────────────────────────────────────────────────────

_PARTITION = {
    'MODULE': 'structural', 'INTERFACE': 'structural', 'PORT': 'structural',
    'MODPORT': 'structural', 'PARAMETER': 'structural', 'PACKAGE': 'structural',
    'CLOCK_DOMAIN': 'structural', 'CLOCKING_BLOCK': 'structural',
    'UVM_TEST': 'verification', 'UVM_ENV': 'verification',
    'UVM_AGENT': 'verification', 'UVM_DRIVER': 'verification',
    'UVM_MONITOR': 'verification', 'UVM_SCOREBOARD': 'verification',
    'UVM_SEQUENCER': 'verification', 'UVM_SEQUENCE': 'verification',
    'UVM_SEQ_ITEM': 'verification', 'CONSTRAINT_BLOCK': 'verification',
    'RAND_VAR': 'verification', 'CONFIG_DB_ENTRY': 'verification',
    'FACTORY_OVERRIDE': 'verification', 'UVM_EVENT': 'verification',
    'COVERGROUP': 'coverage', 'COVERPOINT': 'coverage', 'ASSERTION': 'coverage',
    'CHECKER': 'coverage', 'SVA_PROPERTY': 'coverage', 'SVA_SEQUENCE': 'coverage',
    'REG_MAP': 'register', 'REG_BLOCK': 'register',
    'REGISTER': 'register', 'REG_FIELD': 'register',
}

KINDS      = sorted(_PARTITION.keys())
LABEL_LIST = ['O'] + [f'B-{k}' for k in KINDS] + [f'I-{k}' for k in KINDS]
LABEL2ID   = {l: i for i, l in enumerate(LABEL_LIST)}
ID2LABEL   = {i: l for i, l in enumerate(LABEL_LIST)}
NUM_LABELS = len(LABEL_LIST)

UVM_KINDS = [
    'UVM_TEST', 'UVM_ENV', 'UVM_AGENT', 'UVM_DRIVER', 'UVM_MONITOR',
    'UVM_SCOREBOARD', 'UVM_SEQUENCER', 'UVM_SEQUENCE', 'UVM_SEQ_ITEM',
    'REG_BLOCK', 'REGISTER', 'REG_FIELD',
]

# ── Dataset ───────────────────────────────────────────────────────────────────

class NERDataset(Dataset):
    def __init__(self, records):
        # Pre-convert to numpy for fast zero-copy tensor wrapping
        self.input_ids = np.array([r['input_ids']      for r in records], dtype=np.int64)
        self.attn_mask = np.array([r['attention_mask'] for r in records], dtype=np.int64)
        self.labels    = np.array([r['labels']         for r in records], dtype=np.int64)

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            'input_ids':      torch.from_numpy(self.input_ids[idx].copy()),
            'attention_mask': torch.from_numpy(self.attn_mask[idx].copy()),
            'labels':         torch.from_numpy(self.labels[idx].copy()),
        }

# ── Evaluation ────────────────────────────────────────────────────────────────

@torch.no_grad()
def evaluate(model, loader, device):
    model.eval()
    all_preds, all_golds = [], []
    for batch in loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        logits = model(**batch).logits
        preds  = logits.argmax(-1).cpu().tolist()
        golds  = batch['labels'].cpu().tolist()
        for p_seq, g_seq in zip(preds, golds):
            p_row, g_row = [], []
            for p, g in zip(p_seq, g_seq):
                if g == -100:
                    continue
                p_row.append(ID2LABEL[p])
                g_row.append(ID2LABEL[g])
            all_preds.append(p_row)
            all_golds.append(g_row)
    report  = classification_report(all_golds, all_preds, output_dict=True, zero_division=0)
    micro_f1 = f1_score(all_golds, all_preds, average='micro', zero_division=0)
    return micro_f1, report

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    random.seed(SEED)
    torch.manual_seed(SEED)

    if torch.backends.mps.is_available():
        device = torch.device('mps')
    elif torch.cuda.is_available():
        device = torch.device('cuda')
    else:
        device = torch.device('cpu')
    print(f"Device: {device}", flush=True)

    print(f"Loading {DATA_PATH} ...", flush=True)
    with open(DATA_PATH) as f:
        records = [json.loads(l) for l in f]
    print(f"  {len(records):,} chunks", flush=True)

    random.shuffle(records)
    split = int(len(records) * TRAIN_SPLIT)
    train_recs, val_recs = records[:split], records[split:]
    del records   # free the Python-list memory before numpy allocation

    print(f"  Pre-converting to numpy ...", flush=True)
    train_ds = NERDataset(train_recs); del train_recs
    val_ds   = NERDataset(val_recs);   del val_recs
    print(f"  Train: {len(train_ds):,}  Val: {len(val_ds):,}", flush=True)

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=0, pin_memory=False)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=False)

    print(f"Loading {MODEL_NAME} → {NUM_LABELS} labels ...", flush=True)
    model = AutoModelForTokenClassification.from_pretrained(
        MODEL_NAME,
        num_labels=NUM_LABELS,
        id2label=ID2LABEL,
        label2id=LABEL2ID,
        ignore_mismatched_sizes=True,
    ).to(device)

    total_steps  = len(train_loader) * EPOCHS
    warmup_steps = int(total_steps * WARMUP_RATIO)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=0.01)
    scheduler = get_linear_schedule_with_warmup(optimizer, warmup_steps, total_steps)

    Path(OUT_DIR).mkdir(parents=True, exist_ok=True)
    best_f1 = 0.0
    print(f"Training {EPOCHS} epochs, {len(train_loader)} steps/epoch", flush=True)

    for epoch in range(1, EPOCHS + 1):
        model.train()
        running_loss = 0.0

        for step, batch in enumerate(train_loader, 1):
            batch = {k: v.to(device) for k, v in batch.items()}
            loss  = model(**batch).loss
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()
            optimizer.zero_grad()
            running_loss += loss.item()

            if step % LOG_EVERY == 0:
                print(f"  E{epoch} step {step}/{len(train_loader)}  loss={running_loss/step:.4f}", flush=True)

        micro_f1, report = evaluate(model, val_loader, device)
        avg_loss = running_loss / len(train_loader)
        print(f"\nEpoch {epoch}  loss={avg_loss:.4f}  val_micro_F1={micro_f1:.4f}", flush=True)

        for k in UVM_KINDS:
            f1  = report.get(k, {}).get('f1-score', 0.0)
            sup = report.get(k, {}).get('support', 0)
            if sup > 0:
                print(f"    {k:<22} F1={f1:.4f}  support={sup}", flush=True)

        struc_f1 = report.get('MODULE', {}).get('f1-score', 0.0)
        print(f"    MODULE                 F1={struc_f1:.4f}  (structural sample)", flush=True)

        if micro_f1 > best_f1:
            best_f1 = micro_f1
            model.save_pretrained(OUT_DIR)
            AutoTokenizer.from_pretrained(MODEL_NAME).save_pretrained(OUT_DIR)
            print(f"  → checkpoint saved  (best={best_f1:.4f})", flush=True)
        print(flush=True)

    print(f"Done. Best val micro-F1: {best_f1:.4f}", flush=True)
    print(f"Model: {OUT_DIR}", flush=True)


if __name__ == '__main__':
    main()
